Document API usage of XtfFileMerger
GeoWerkstatt/interlis-testbed-runner pull request #12
Opened 2024-04-10 13:41 UTC by domi-b

Resolves #9

2024-04-10 14:48 UTC, Philippluca requested changes

2024-04-10 14:48 UTC, Philippluca commented on src/main/java/ch/geowerkstatt/interlis/testbed/runner/xtf/XtfFileMerger.java
> +     * The resulting data will be written to the output file.
REQ: Dokumentieren auf welche XML attribute geschaut wird & wie die einzelnen XTF Objekte identifiziert werden (OID?). 
Ev. kleines Beispiel für die 3 Operationen hier oder im Readme.md

2024-04-11 06:56 UTC, domi-b commented on src/main/java/ch/geowerkstatt/interlis/testbed/runner/xtf/XtfFileMerger.java
> +     * The resulting data will be written to the output file.
Im Readme gibt es bereits eine kurze Beschreibung mit Beispielen dazu, ich habe hier im Kommentar noch die XML-Attribute ergänzt.

2024-04-12 10:10 UTC, Philippluca approved these changes

2024-04-15 05:47 UTC, merged