Merge partial transfer files with base data
GeoWerkstatt/interlis-testbed-runner pull request #2
Opened 2023-12-07 14:05 UTC by domi-b

Merges base data file and patch file into a merged XTF file.

Integration into the Runner will be implemented later.

2023-12-07 15:21 UTC, Philippluca requested changes

2023-12-07 15:21 UTC, Philippluca commented on src/test/data/xtf-merger/data.xtf
> +                <attr2>Some more text</attr2>
REQ: Testaten um verschachtelte attributes erweitern. z.B. Polygon mit 3 coord Einträgen.

2023-12-07 15:21 UTC, Philippluca commented on src/test/java/ch/geowerkstatt/interlis/testbed/runner/xtf/XtfFileMergerTest.java
> +        assertIterableEquals(List.of("A1"), b2.objects().keySet());
REQ: Content der Baskets auch überprüfen.
PP: Ein expected xtf. als Verlgeich erstellen.

2023-12-07 15:21 UTC, Philippluca commented on src/main/java/ch/geowerkstatt/interlis/testbed/runner/xtf/XtfFileMerger.java
> +    public boolean merge(Path baseFile, Path patchFile, Path outputFile) {
Q: Sehe ich richtig, dass nur `add`, `replace` als Operationen möglich sind? Das delete fehlt noch?

2023-12-07 15:21 UTC, Philippluca commented on src/test/data/xtf-merger/data.xtf
> +                <attr2>Some more text</attr2>
PP: Add und Replace (später delete Operationen) als eigene kleinere Testcases beschreiben.

2023-12-11 09:53 UTC, domi-b commented on src/main/java/ch/geowerkstatt/interlis/testbed/runner/xtf/XtfFileMerger.java
> +    public boolean merge(Path baseFile, Path patchFile, Path outputFile) {
Delete habe ich noch hinzugefügt. Sobald ein Basket oder Objekt ein Attribute `delete` oder `DELETE` hat, wird es gelöscht (der Wert des Attributes wird ignoriert).

2023-12-11 10:47 UTC, Philippluca approved these changes

2023-12-11 12:31 UTC, merged